language: go

go:
  - 1.x
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get -v github.com/golang/lint/golint

script:
  - ./scripts/pre-commit.sh
  - go test -cpu=1,2 -v -race ./...

notifications:
  email: false
